Notes: Jenkins pipeline
project: bento
services:
  backend:
    version: 4.10.0.294
    image: 4.10.0.294
    buildNumber: '294'
  frontend:
    version: 4.2.0.222
    image: 4.2.0.222
    buildNumber: '222'
  authN:
    version: 2.4.0.61
    image: 2.4.0.61
    buildNumber: '61'
  files:
    version: null
    image: null
    buildNumber: '2'
    additionalProperties: null
  authZ:
    version: 1.3.1.80
    image: 1.3.1.80
    buildNumber: '80'
