name: Deploy CDK Stack
permissions: 
  contents: write
  id-token: write
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
jobs:
  build:
    name: Deploy Bento
    runs-on: ubuntu-latest
    # env:
    #     ECR_REPOSITORY: bento-frontend
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: "20"
 
    - name: Install Python dependencies and CDK
      run: |
        python -m pip install --upgrade pip
        # install stack Python dependencies
        cd awscdk/bento && pip3 install --ignore-installed --break-system-packages -r requirements.txt
        npm install -g aws-cdk@2.155.0

    - name: AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: ${{ github.actor }}
    
    - name: Get ini file
      run: |
        aws s3api get-object --bucket fnl-bento-cdk-config --key config.ini.cdk ./awscdk/bento/config.ini

    - name: Debug
      env:
        AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      id: debug-steps
      run: |
        ls -la awscdk/bento
        cd awscdk/bento && cdk synth

    # - name: Build Config File
    #   id: build-config-file
    #   run: |
    #     echo "[main]" >> config.ini
    #     echo "vpc_id =" >> config.ini

    # - name: Slack Notification
    #   uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #     steps: ${{ toJson(steps) }}
    #   if: always()