name: Bento CDK Deploy
permissions: 
  contents: write
  id-token: write
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      frontend_image:
      backend_image:
      files_image:
      authn_image:
      authz_image:
      cdk_command:
        description: 'Which CDK Command To Run'
        required: true
        default: 'synth'
        type: choice
        options:
          - synth
          - diff
          - deploy
jobs:
  build:
    name: Deploy Bento
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: "20"
 
    - name: Install Python dependencies and CDK
      run: |
        python -m pip install --upgrade pip
        # install stack Python dependencies
        cd awscdk/bento && pip3 install --ignore-installed --break-system-packages -r requirements.txt
        npm install -g aws-cdk@2.155.0

    - name: AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: ${{ github.actor }}
    
    - name: Get config files
      env:
        ENV_NAME: ${{ inputs.environment }}
        FRONTEND_IMAGE: ${{ inputs.frontend_image }}
        BACKEND_IMAGE: ${{ inputs.backend_image }}
        FILES_IMAGE: ${{ inputs.files_image }}
        AUTHN_IMAGE: ${{ inputs.authn_image }}
        AUTHZ_IMAGE: ${{ inputs.authz_image }}
      run: |
        cd awscdk/bento/
        aws s3api get-object --bucket fnl-bento-cdk-config --key config.ini.$ENV_NAME ./config.ini.$ENV_NAME

        git fetch
        git show $ENV_NAME:deployments.yaml > ./deployments.yaml

        vars=$(python3 parseYML.py)
        for v in $vars; do command="export $v"; eval $command;  done

        FRONTEND_IMAGE="${FRONTEND_IMAGE:-$IMAGE_FRONTEND}"
        BACKEND_IMAGE="${BACKEND_IMAGE:-$IMAGE_BACKEND}"
        FILES_IMAGE="${FILES_IMAGE:-$IMAGE_FILES}"
        AUTHN_IMAGE="${AUTHN_IMAGE:-$IMAGE_AUTHN}"
        AUTHZ_IMAGE="${AUTHZ_IMAGE:-$IMAGE_AUTHZ}"
        
        envsubst < config.ini.$ENV_NAME > config.ini

    - name: Execute CDK
      env:
        AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        ENV_NAME: ${{ inputs.environment }}
        CDK_CMD: ${{ inputs.cdk_command }}
      run: |

        cd awscdk/bento && cdk $CDK_CMD --require-approval=never

    # - name: Slack Notification
    #   uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #     steps: ${{ toJson(steps) }}
    #   if: always()