name: Deploy CDK Stack
permissions: 
  contents: write
  id-token: write
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      frontend_image:
      backend_image:
      files_image:
      authn_image:
      authz_image:
jobs:
  build:
    name: Deploy Bento
    runs-on: ubuntu-latest
    # env:
    #     ECR_REPOSITORY: bento-frontend
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: "20"
 
    - name: Install Python dependencies and CDK
      run: |
        python -m pip install --upgrade pip
        # install stack Python dependencies
        cd awscdk/bento && pip3 install --ignore-installed --break-system-packages -r requirements.txt
        npm install -g aws-cdk@2.155.0

    - name: AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: ${{ github.actor }}
    
    - name: Get config files
      env:
        ENV_NAME: ${{ inputs.environment }}
        FRONTEND_IMAGE: ${{ inputs.frontend_image }}
        BACKEND_IMAGE: ${{ inputs.backend_image }}
        FILES_IMAGE: ${{ inputs.files_image }}
        AUTHN_IMAGE: ${{ inputs.authn_image }}
        AUTHZ_IMAGE: ${{ inputs.authz_image }}
      run: |
        cd awscdk/bento/
        aws s3api get-object --bucket fnl-bento-cdk-config --key config.ini.$ENV_NAME ./config.ini.$ENV_NAME

        git fetch
        git show $ENV_NAME:deployments.yaml > deployments.yaml

        vars=$(python3 parseYML.py)
        for v in $vars; do command="export $v"; eval $command;  done

        FRONTEND_IMAGE="${FRONTEND_IMAGE:-$FRONTEND_IMAGE_VALUE}"
        BACKEND_IMAGE="${BACKEND_IMAGE:-$BACKEND_IMAGE_VALUE}"
        FILES_IMAGE="${FILES_IMAGE:-$FILES_IMAGE_VALUE}"
        AUTHN_IMAGE="${AUTHN_IMAGE:-$AUTHN_IMAGE_VALUE}"
        AUTHZ_IMAGE="${AUTHZ_IMAGE:-$AUTHZ_IMAGE_VALUE}"

        envsubst < config.ini.$ENV_NAME > config.ini

    - name: Debug
      env:
        AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        ENV_NAME: ${{ inputs.environment }}
      id: debug-steps
      run: |
        ls -la
        ls -la awscdk/bento

        cd awscdk/bento && cdk diff && cdk synth
        # cd awscdk/bento && cdk synth

    # - name: Build Config File
    #   id: build-config-file
    #   run: |
    #     echo "[main]" >> config.ini
    #     echo "vpc_id =" >> config.ini

    # - name: Slack Notification
    #   uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #     steps: ${{ toJson(steps) }}
    #   if: always()